### PR TITLE
Change Puppet[:user] and Puppet[:group] to those of the user running the test

### PR DESCRIPTION
**Pull request by mmarod**
This is my fix for #15.

The problem seemed to boil down to the fact that Puppet[:user] and Puppet[:group] don't change to the running user during the apply. In this commit, I grab the user running the script and their primary group using Ruby's Etc module before the apply occurs.

It's a bit hacky but it gets me through the tests as non-root.

### CODE REVIEW

**Comment by mmarod** [comment]
Any thoughts on this?

**Comment by nhemingway** [comment]
This PR also fixes the problem for me.

Having cloned and also applied this PR, the tests all pass (ruby 2.3.1).  Is there a blocker to merging this and cutting a release?

I note that the failing travis tests are for rubies 1.8 and 1.9.  Aren't they both deprecated by puppet now>

**Comment by sirinek** [comment]
@nhemingway at what point can we just create a 0.5.0 on our own? The last release was over 3 years ago.

**Comment by nhemingway** [comment]
Apologies, but I'm not tracking the module any more - I've changed jobs and
$newjob doesn't use puppet at all.  It's a shame, cos it's a useful tool.

Neil

**Pull request closed without merging**
